required = ["git.apache.org/thrift.git/lib/go/thrift"]

[[constraint]]
  name = "github.com/paypal/gorealis"
  branch = "drainSLA"
  source = "github.com/rdelval/gorealis"

[[constraint]]
  name = "github.com/spf13/cobra"
  revision = "fe5e611709b0c57fa4a89136deaa8e1d4004d053"

[[constraint]]
  name = "github.com/spf13/viper"
  revision = "62edee319679b6ceaec16de03b966102d2dea709"

[[constraint]]
    name = "git.apache.org/thrift.git"
    branch = "0.10.0-http-client-fix"
    source = "github.com/rdelval/thrift"
